Feature/공공데이터api
Charging-Life/BACK-END pull request #3
Opened 2022-08-07 08:12 UTC by kathyleesh

공공데이터 api를 불러와서 저장하였습니다.

2022-08-08 14:48 UTC, star-sil requested changes
코드 리뷰 보시고 코드 수정 부탁드립니다.
다음에는 Reviewer 등록 부탁드릴게요.

2022-08-08 14:48 UTC, star-sil commented on src/main/java/com/example/charging_life/station/StationController.java
> +        return "success";
swagger에 적용하기 위해 ResponseEntity로 맵핑해서 응답 및 해당 api에 대한 요약 및 간단한 설명(요약이 명료하면 생략가능) 부탁드리겠습니다.

참고할 코드 예시입니다.
https://github.com/Charging-Life/BACK-END/blob/cf45789556738aee94bbe7538aa300aefb0553ed/src/main/java/com/example/charging_life/member/MemberController.java#L36-L43

2022-08-08 14:48 UTC, star-sil commented on src/main/java/com/example/charging_life/station/entity/ChargingStation.java
>          this.location = location;
생성자가 두개 있는데 실행하는데 문제가 없나요?
<<<<< HEAD 및 ======= 같은 코드는 필요하지 않다면 삭제 부탁드립니다.

2022-08-10 14:06 UTC, kathyleesh commented on src/main/java/com/example/charging_life/station/entity/ChargingStation.java
>          this.location = location;
충돌나서 해결했던 부분이 보여져서 그런 것 같습니다!
다음번에 올릴땐 보이지 않게 올리도록 하겠습니다!

2022-08-10 14:06 UTC, kathyleesh commented on src/main/java/com/example/charging_life/station/StationController.java
> +        return "success";
swagger 추가 설정해서 올리도록 하겠습니다!

2022-08-10 14:06 UTC, kathyleesh commented on src/main/java/com/example/charging_life/station/StationController.java
> +        return "success";
swagger 추가 설정해서 올리도록 하겠습니다!

2022-08-10 14:36 UTC, star-sil commented on src/main/java/com/example/charging_life/station/entity/ChargingStation.java
>          this.location = location;
넵넵 pull request 수정해주세요!!

2022-08-12 12:02 UTC, merged